### ISSUE TITLE
不准确的"right_example"

### ISSUE THREAD

**Issue by Cerulime** [SUSTech-HPCLab/CS305-2024Spring-Assignment1#1]
https://github.com/SUSTech-HPCLab/CS305-2024Spring-Assignment1/blob/4b459e581c60e2415334b6d4765dc504d469418e/img/right_example.png

在该图片中，观察到AUTHORITY SECTION第一条记录和ADDITIONAL SECTION第一条记录有异常，判断ancount少1，正确的结果应当将整体rr记录上移一位

**Comment by EricLee543** [comment]
Thanks for your issue. Already fixed.
